# Start your image with a node base image
FROM python:3.13-rc-bookworm⁠
# Decision: Use Python, not Ubuntu to keep it lightweight.

# This instruction specifies the "working directory" or the path in the image where files will be copied and commands will be executed.
WORKDIR /app

# Copy the requirements file and install dependencies
# This instruction tells the builder to copy files from the host and put them into the container image.
COPY requirements.txt 
# This instruction tells the builder to run the specified command.
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app into the docker directory
COPY PythonApp.py
COPY SAP_LLM_Llama.py
COPY Signal_test_private.py
COPY signavio-credentials.txt
COPY sap-llm-credentials.txt

# Command to run the App
CMD ["python", "run", "PythonApp.py"]



# Copy in the source code
COPY src ./src
# EXPOSE 5000

# Expose the port that Streamlit will run on
# EXPOSE 8501

# Command to run the Streamlit app
# CMD ["streamlit", "run", "PythonApp.py"]